const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const typeRouter = require('./typeRouter')
const factoryRouter = require('./factoryRouter')
const collectionRouter = require('./collectionRouter')
const productRouter = require('./productRouter')
const featureRouter = require('./featureRouter')
const subtypeRouter = require('./subtypeRouter')
const contactsRouter = require('./contactsRouter')
const contentRouter = require('./contentRouter')
const orderRouter = require('./orderRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/factory', factoryRouter)
router.use('/collection', collectionRouter)
router.use('/product', productRouter)
router.use('/feature', featureRouter)
router.use('/subtype', subtypeRouter)
router.use('/contacts', contactsRouter)
router.use('/content', contentRouter)
router.use('/order', orderRouter)

module.exports = router