-- Удаляем все таблицы
DROP TABLE IF EXISTS product_infos CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS basket_products CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS types CASCADE;
DROP TABLE IF EXISTS factories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS baskets CASCADE;
DROP TABLE IF EXISTS subtypes CASCADE;
DROP TABLE IF EXISTS feature_type_factories CASCADE;
DROP TABLE IF EXISTS SequelizeMeta CASCADE; 